language: ruby

services:
  - docker

before_install:
  - docker build -t adesharn/docker-boilerplate -f Dockerfile.dev .

script:
  - docker run -e CI=true adesharn/docker-boilerplate npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker-boilerplate'
  env: 'DockerBoilerplate-env'
  bucket: 'elasticbeanstalk-us-east-1-726707159798'
  bucket_path: 'docker-boilerplate'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
